title: Cooper Sullivan
paginate: 5
theme: "PaperMod"

params:
    title: Cooper Sullivan
    description: "An e-portfolio for some of my projects & programs."
    keywords: [Blog, Portfolio, PaperMod]
    author: Cooper Sullivan
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        disableFingerprinting: true
        favicon: "https://i.imgur.com/V3WyarA.png"
        favicon16x16: "https://i.imgur.com/sYXAGAB.png"
        favicon32x32: "https://i.imgur.com/w5k0qry.png"
        apple_touch_icon: "https://i.imgur.com/V3WyarA.png"
        safari_pinned_tab: "https://i.imgur.com/V3WyarA.png"

    label:
        text: "Cooper Sullivan"
        icon: #/apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Cooper Sullivan
        subtitle: "This website serves as an e-portfolio for some of my projects & programs."
        imageUrl: "https://i.imgur.com/jeOyUpL.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: Cooper Sullivan
        buttons:
            - name: View Projects
              url: projects

    socialIcons:
        - name: twitter
          url: "https://twitter.com/coopersully/"
        - name: stackoverflow
          url: "https://stackoverflow.com/users/15706415/cooper-sullivan/"
        - name: github
          url: "https://github.com/coopersully/"
#        - name: discord
#          url: "https://discord.com/invite/best-server/"
#        - name: email
#          url: "thecoopersully@gmail.com"
        - name: instagram
          url: "https://instagram.com/coopersully"
        - name: snapchat
          url: "https://snapchat.com/add/coopersully"
        - name: spotify
          url: "https://open.spotify.com/user/coopersully?si=880fd722b6a5495d"
        - name: twitch
          url: "https://twitch.tv/cursedimpulse"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/coopersully/coopersully.me/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: home
          name: home
          url: 
          weight: 10
        - identifier: projects
          name: projects
          url: /projects/
          weight: 20
        - identifier: tags
          name: tags
          url: /tags/
          weight: 30
        - identifier: search
          name: search
          url: /search/
          weight: 40
          
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
